// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/nquangtrung/agentgo/providers/claude (interfaces: claudeChatService)
//
// Generated by this command:
//
//	mockgen -destination=./mocks/mock_claude_chat_service.go -package=mocks github.com/nquangtrung/agentgo/providers/claude claudeChatService
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	openai "github.com/openai/openai-go/v3"
	option "github.com/openai/openai-go/v3/option"
	ssestream "github.com/openai/openai-go/v3/packages/ssestream"
	gomock "go.uber.org/mock/gomock"
)

// MockclaudeChatService is a mock of claudeChatService interface.
type MockclaudeChatService struct {
	ctrl     *gomock.Controller
	recorder *MockclaudeChatServiceMockRecorder
	isgomock struct{}
}

// MockclaudeChatServiceMockRecorder is the mock recorder for MockclaudeChatService.
type MockclaudeChatServiceMockRecorder struct {
	mock *MockclaudeChatService
}

// NewMockclaudeChatService creates a new mock instance.
func NewMockclaudeChatService(ctrl *gomock.Controller) *MockclaudeChatService {
	mock := &MockclaudeChatService{ctrl: ctrl}
	mock.recorder = &MockclaudeChatServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockclaudeChatService) EXPECT() *MockclaudeChatServiceMockRecorder {
	return m.recorder
}

// New mocks base method.
func (m *MockclaudeChatService) New(ctx context.Context, body openai.ChatCompletionNewParams, opts ...option.RequestOption) (*openai.ChatCompletion, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, body}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "New", varargs...)
	ret0, _ := ret[0].(*openai.ChatCompletion)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// New indicates an expected call of New.
func (mr *MockclaudeChatServiceMockRecorder) New(ctx, body any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, body}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "New", reflect.TypeOf((*MockclaudeChatService)(nil).New), varargs...)
}

// NewStreaming mocks base method.
func (m *MockclaudeChatService) NewStreaming(ctx context.Context, body openai.ChatCompletionNewParams, opts ...option.RequestOption) *ssestream.Stream[openai.ChatCompletionChunk] {
	m.ctrl.T.Helper()
	varargs := []any{ctx, body}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "NewStreaming", varargs...)
	ret0, _ := ret[0].(*ssestream.Stream[openai.ChatCompletionChunk])
	return ret0
}

// NewStreaming indicates an expected call of NewStreaming.
func (mr *MockclaudeChatServiceMockRecorder) NewStreaming(ctx, body any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, body}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "NewStreaming", reflect.TypeOf((*MockclaudeChatService)(nil).NewStreaming), varargs...)
}
