// Code generated by MockGen. DO NOT EDIT.
// Source: trontria.com/agentgo/providers/openai (interfaces: asFunctionCaller)
//
// Generated by this command:
//
//	mockgen -destination=./mocks/mock_as_function_caller.go -package=mocks trontria.com/agentgo/providers/openai asFunctionCaller
//

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	responses "github.com/openai/openai-go/v3/responses"
	gomock "go.uber.org/mock/gomock"
)

// MockasFunctionCaller is a mock of asFunctionCaller interface.
type MockasFunctionCaller struct {
	ctrl     *gomock.Controller
	recorder *MockasFunctionCallerMockRecorder
	isgomock struct{}
}

// MockasFunctionCallerMockRecorder is the mock recorder for MockasFunctionCaller.
type MockasFunctionCallerMockRecorder struct {
	mock *MockasFunctionCaller
}

// NewMockasFunctionCaller creates a new mock instance.
func NewMockasFunctionCaller(ctrl *gomock.Controller) *MockasFunctionCaller {
	mock := &MockasFunctionCaller{ctrl: ctrl}
	mock.recorder = &MockasFunctionCallerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockasFunctionCaller) EXPECT() *MockasFunctionCallerMockRecorder {
	return m.recorder
}

// AsFunctionCall mocks base method.
func (m *MockasFunctionCaller) AsFunctionCall() responses.ResponseFunctionToolCall {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AsFunctionCall")
	ret0, _ := ret[0].(responses.ResponseFunctionToolCall)
	return ret0
}

// AsFunctionCall indicates an expected call of AsFunctionCall.
func (mr *MockasFunctionCallerMockRecorder) AsFunctionCall() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AsFunctionCall", reflect.TypeOf((*MockasFunctionCaller)(nil).AsFunctionCall))
}
