// Code generated by MockGen. DO NOT EDIT.
// Source: trontria.com/agentgo/providers/openai (interfaces: openAIResponsesService)
//
// Generated by this command:
//
//	mockgen -destination=./mocks/mock_open_ai_response.go -package=mocks trontria.com/agentgo/providers/openai openAIResponsesService
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	option "github.com/openai/openai-go/v3/option"
	ssestream "github.com/openai/openai-go/v3/packages/ssestream"
	responses "github.com/openai/openai-go/v3/responses"
	gomock "go.uber.org/mock/gomock"
)

// MockopenAIResponsesService is a mock of openAIResponsesService interface.
type MockopenAIResponsesService struct {
	ctrl     *gomock.Controller
	recorder *MockopenAIResponsesServiceMockRecorder
	isgomock struct{}
}

// MockopenAIResponsesServiceMockRecorder is the mock recorder for MockopenAIResponsesService.
type MockopenAIResponsesServiceMockRecorder struct {
	mock *MockopenAIResponsesService
}

// NewMockopenAIResponsesService creates a new mock instance.
func NewMockopenAIResponsesService(ctrl *gomock.Controller) *MockopenAIResponsesService {
	mock := &MockopenAIResponsesService{ctrl: ctrl}
	mock.recorder = &MockopenAIResponsesServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockopenAIResponsesService) EXPECT() *MockopenAIResponsesServiceMockRecorder {
	return m.recorder
}

// New mocks base method.
func (m *MockopenAIResponsesService) New(ctx context.Context, body responses.ResponseNewParams, opts ...option.RequestOption) (*responses.Response, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, body}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "New", varargs...)
	ret0, _ := ret[0].(*responses.Response)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// New indicates an expected call of New.
func (mr *MockopenAIResponsesServiceMockRecorder) New(ctx, body any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, body}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "New", reflect.TypeOf((*MockopenAIResponsesService)(nil).New), varargs...)
}

// NewStreaming mocks base method.
func (m *MockopenAIResponsesService) NewStreaming(ctx context.Context, body responses.ResponseNewParams, opts ...option.RequestOption) *ssestream.Stream[responses.ResponseStreamEventUnion] {
	m.ctrl.T.Helper()
	varargs := []any{ctx, body}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "NewStreaming", varargs...)
	ret0, _ := ret[0].(*ssestream.Stream[responses.ResponseStreamEventUnion])
	return ret0
}

// NewStreaming indicates an expected call of NewStreaming.
func (mr *MockopenAIResponsesServiceMockRecorder) NewStreaming(ctx, body any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, body}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "NewStreaming", reflect.TypeOf((*MockopenAIResponsesService)(nil).NewStreaming), varargs...)
}
