// Code generated by MockGen. DO NOT EDIT.
// Source: trontria.com/agentgo/providers (interfaces: AgentProvider)
//
// Generated by this command:
//
//	mockgen -destination=../mocks/mock_agent_provider.go -package=mocks trontria.com/agentgo/providers AgentProvider
//

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
	models "trontria.com/agentgo/models"
	providers "trontria.com/agentgo/providers"
)

// MockAgentProvider is a mock of AgentProvider interface.
type MockAgentProvider struct {
	ctrl     *gomock.Controller
	recorder *MockAgentProviderMockRecorder
	isgomock struct{}
}

// MockAgentProviderMockRecorder is the mock recorder for MockAgentProvider.
type MockAgentProviderMockRecorder struct {
	mock *MockAgentProvider
}

// NewMockAgentProvider creates a new mock instance.
func NewMockAgentProvider(ctrl *gomock.Controller) *MockAgentProvider {
	mock := &MockAgentProvider{ctrl: ctrl}
	mock.recorder = &MockAgentProviderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAgentProvider) EXPECT() *MockAgentProviderMockRecorder {
	return m.recorder
}

// GenerateText mocks base method.
func (m *MockAgentProvider) GenerateText(params providers.AgentProviderGenerateTextParams) (models.LanguageModelOutput, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GenerateText", params)
	ret0, _ := ret[0].(models.LanguageModelOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GenerateText indicates an expected call of GenerateText.
func (mr *MockAgentProviderMockRecorder) GenerateText(params any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GenerateText", reflect.TypeOf((*MockAgentProvider)(nil).GenerateText), params)
}

// GetContext mocks base method.
func (m *MockAgentProvider) GetContext() models.LanguageModelContext {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetContext")
	ret0, _ := ret[0].(models.LanguageModelContext)
	return ret0
}

// GetContext indicates an expected call of GetContext.
func (mr *MockAgentProviderMockRecorder) GetContext() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetContext", reflect.TypeOf((*MockAgentProvider)(nil).GetContext))
}

// ResolveToolCalls mocks base method.
func (m *MockAgentProvider) ResolveToolCalls(params providers.AgentProviderPromptMessageParams, toolParams []models.Tool) ([]models.ToolCall, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ResolveToolCalls", params, toolParams)
	ret0, _ := ret[0].([]models.ToolCall)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ResolveToolCalls indicates an expected call of ResolveToolCalls.
func (mr *MockAgentProviderMockRecorder) ResolveToolCalls(params, toolParams any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ResolveToolCalls", reflect.TypeOf((*MockAgentProvider)(nil).ResolveToolCalls), params, toolParams)
}

// StreamText mocks base method.
func (m *MockAgentProvider) StreamText(params providers.AgentProviderStreamTextParams, channel chan models.Part) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "StreamText", params, channel)
}

// StreamText indicates an expected call of StreamText.
func (mr *MockAgentProviderMockRecorder) StreamText(params, channel any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "StreamText", reflect.TypeOf((*MockAgentProvider)(nil).StreamText), params, channel)
}
