// Code generated by MockGen. DO NOT EDIT.
// Source: trontria.com/agentgo/models (interfaces: Part)
//
// Generated by this command:
//
//	mockgen -destination=../mocks/mock_part.go -package=mocks trontria.com/agentgo/models Part
//

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
	models "trontria.com/agentgo/models"
)

// MockPart is a mock of Part interface.
type MockPart struct {
	ctrl     *gomock.Controller
	recorder *MockPartMockRecorder
	isgomock struct{}
}

// MockPartMockRecorder is the mock recorder for MockPart.
type MockPartMockRecorder struct {
	mock *MockPart
}

// NewMockPart creates a new mock instance.
func NewMockPart(ctrl *gomock.Controller) *MockPart {
	mock := &MockPart{ctrl: ctrl}
	mock.recorder = &MockPartMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPart) EXPECT() *MockPartMockRecorder {
	return m.recorder
}

// Context mocks base method.
func (m *MockPart) Context() models.LanguageModelContext {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Context")
	ret0, _ := ret[0].(models.LanguageModelContext)
	return ret0
}

// Context indicates an expected call of Context.
func (mr *MockPartMockRecorder) Context() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Context", reflect.TypeOf((*MockPart)(nil).Context))
}

// ModelName mocks base method.
func (m *MockPart) ModelName() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ModelName")
	ret0, _ := ret[0].(string)
	return ret0
}

// ModelName indicates an expected call of ModelName.
func (mr *MockPartMockRecorder) ModelName() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ModelName", reflect.TypeOf((*MockPart)(nil).ModelName))
}

// Type mocks base method.
func (m *MockPart) Type() models.PartType {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Type")
	ret0, _ := ret[0].(models.PartType)
	return ret0
}

// Type indicates an expected call of Type.
func (mr *MockPartMockRecorder) Type() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Type", reflect.TypeOf((*MockPart)(nil).Type))
}

// isPart mocks base method.
func (m *MockPart) isPart() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "isPart")
}

// isPart indicates an expected call of isPart.
func (mr *MockPartMockRecorder) isPart() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "isPart", reflect.TypeOf((*MockPart)(nil).isPart))
}
