// Code generated by MockGen. DO NOT EDIT.
// Source: trontria.com/agentgo/providers (interfaces: AgentProvider)
//
// Generated by this command:
//
//	mockgen -destination=../mocks/mock_agent_provider.go -package=mocks trontria.com/agentgo/providers AgentProvider
//

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
	models "trontria.com/agentgo/models"
	providers "trontria.com/agentgo/providers"
)

// MockAgentProvider is a mock of AgentProvider interface.
type MockAgentProvider struct {
	ctrl     *gomock.Controller
	recorder *MockAgentProviderMockRecorder
	isgomock struct{}
}

// MockAgentProviderMockRecorder is the mock recorder for MockAgentProvider.
type MockAgentProviderMockRecorder struct {
	mock *MockAgentProvider
}

// NewMockAgentProvider creates a new mock instance.
func NewMockAgentProvider(ctrl *gomock.Controller) *MockAgentProvider {
	mock := &MockAgentProvider{ctrl: ctrl}
	mock.recorder = &MockAgentProviderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAgentProvider) EXPECT() *MockAgentProviderMockRecorder {
	return m.recorder
}

// Context mocks base method.
func (m *MockAgentProvider) Context() models.LanguageModelContext {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Context")
	ret0, _ := ret[0].(models.LanguageModelContext)
	return ret0
}

// Context indicates an expected call of Context.
func (mr *MockAgentProviderMockRecorder) Context() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Context", reflect.TypeOf((*MockAgentProvider)(nil).Context))
}

// GenerateText mocks base method.
func (m *MockAgentProvider) GenerateText(params providers.AgentProviderPromptMessageParams) (models.LanguageModelOutput, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GenerateText", params)
	ret0, _ := ret[0].(models.LanguageModelOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GenerateText indicates an expected call of GenerateText.
func (mr *MockAgentProviderMockRecorder) GenerateText(params any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GenerateText", reflect.TypeOf((*MockAgentProvider)(nil).GenerateText), params)
}

// ResolveToolCall mocks base method.
func (m *MockAgentProvider) ResolveToolCall(params providers.AgentProviderPromptMessageParams, toolParams []models.Tool) *models.ToolCall {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ResolveToolCall", params, toolParams)
	ret0, _ := ret[0].(*models.ToolCall)
	return ret0
}

// ResolveToolCall indicates an expected call of ResolveToolCall.
func (mr *MockAgentProviderMockRecorder) ResolveToolCall(params, toolParams any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ResolveToolCall", reflect.TypeOf((*MockAgentProvider)(nil).ResolveToolCall), params, toolParams)
}

// StreamText mocks base method.
func (m *MockAgentProvider) StreamText(params providers.AgentProviderPromptMessageParams, channel chan models.Part) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "StreamText", params, channel)
}

// StreamText indicates an expected call of StreamText.
func (mr *MockAgentProviderMockRecorder) StreamText(params, channel any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "StreamText", reflect.TypeOf((*MockAgentProvider)(nil).StreamText), params, channel)
}
