// Code generated by MockGen. DO NOT EDIT.
// Source: trontria.com/agentgo/models (interfaces: AsPart)
//
// Generated by this command:
//
//	mockgen -destination=../mocks/mock_as_part.go -package=mocks trontria.com/agentgo/models AsPart
//

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
	models "trontria.com/agentgo/models"
)

// MockAsPart is a mock of AsPart interface.
type MockAsPart struct {
	ctrl     *gomock.Controller
	recorder *MockAsPartMockRecorder
	isgomock struct{}
}

// MockAsPartMockRecorder is the mock recorder for MockAsPart.
type MockAsPartMockRecorder struct {
	mock *MockAsPart
}

// NewMockAsPart creates a new mock instance.
func NewMockAsPart(ctrl *gomock.Controller) *MockAsPart {
	mock := &MockAsPart{ctrl: ctrl}
	mock.recorder = &MockAsPartMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAsPart) EXPECT() *MockAsPartMockRecorder {
	return m.recorder
}

// AsStepEndPart mocks base method.
func (m *MockAsPart) AsStepEndPart() (models.StepEndPart, bool) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AsStepEndPart")
	ret0, _ := ret[0].(models.StepEndPart)
	ret1, _ := ret[1].(bool)
	return ret0, ret1
}

// AsStepEndPart indicates an expected call of AsStepEndPart.
func (mr *MockAsPartMockRecorder) AsStepEndPart() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AsStepEndPart", reflect.TypeOf((*MockAsPart)(nil).AsStepEndPart))
}

// AsStepStartPart mocks base method.
func (m *MockAsPart) AsStepStartPart() (models.StepStartPart, bool) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AsStepStartPart")
	ret0, _ := ret[0].(models.StepStartPart)
	ret1, _ := ret[1].(bool)
	return ret0, ret1
}

// AsStepStartPart indicates an expected call of AsStepStartPart.
func (mr *MockAsPartMockRecorder) AsStepStartPart() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AsStepStartPart", reflect.TypeOf((*MockAsPart)(nil).AsStepStartPart))
}

// AsTextPart mocks base method.
func (m *MockAsPart) AsTextPart() (models.TextPart, bool) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AsTextPart")
	ret0, _ := ret[0].(models.TextPart)
	ret1, _ := ret[1].(bool)
	return ret0, ret1
}

// AsTextPart indicates an expected call of AsTextPart.
func (mr *MockAsPartMockRecorder) AsTextPart() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AsTextPart", reflect.TypeOf((*MockAsPart)(nil).AsTextPart))
}

// AsToolErrorPart mocks base method.
func (m *MockAsPart) AsToolErrorPart() (models.ToolErrorPart, bool) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AsToolErrorPart")
	ret0, _ := ret[0].(models.ToolErrorPart)
	ret1, _ := ret[1].(bool)
	return ret0, ret1
}

// AsToolErrorPart indicates an expected call of AsToolErrorPart.
func (mr *MockAsPartMockRecorder) AsToolErrorPart() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AsToolErrorPart", reflect.TypeOf((*MockAsPart)(nil).AsToolErrorPart))
}

// AsToolResultPart mocks base method.
func (m *MockAsPart) AsToolResultPart() (models.ToolResultPart, bool) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AsToolResultPart")
	ret0, _ := ret[0].(models.ToolResultPart)
	ret1, _ := ret[1].(bool)
	return ret0, ret1
}

// AsToolResultPart indicates an expected call of AsToolResultPart.
func (mr *MockAsPartMockRecorder) AsToolResultPart() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AsToolResultPart", reflect.TypeOf((*MockAsPart)(nil).AsToolResultPart))
}

// AsToolStartPart mocks base method.
func (m *MockAsPart) AsToolStartPart() (models.ToolPart, bool) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AsToolStartPart")
	ret0, _ := ret[0].(models.ToolPart)
	ret1, _ := ret[1].(bool)
	return ret0, ret1
}

// AsToolStartPart indicates an expected call of AsToolStartPart.
func (mr *MockAsPartMockRecorder) AsToolStartPart() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AsToolStartPart", reflect.TypeOf((*MockAsPart)(nil).AsToolStartPart))
}
