// Code generated by MockGen. DO NOT EDIT.
// Source: trontria.com/agentgo/models (interfaces: StartPart)
//
// Generated by this command:
//
//	mockgen -destination=../mocks/mock_start_part.go -package=mocks trontria.com/agentgo/models StartPart
//

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"
	time "time"

	gomock "go.uber.org/mock/gomock"
)

// MockStartPart is a mock of StartPart interface.
type MockStartPart struct {
	ctrl     *gomock.Controller
	recorder *MockStartPartMockRecorder
	isgomock struct{}
}

// MockStartPartMockRecorder is the mock recorder for MockStartPart.
type MockStartPartMockRecorder struct {
	mock *MockStartPart
}

// NewMockStartPart creates a new mock instance.
func NewMockStartPart(ctrl *gomock.Controller) *MockStartPart {
	mock := &MockStartPart{ctrl: ctrl}
	mock.recorder = &MockStartPartMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockStartPart) EXPECT() *MockStartPartMockRecorder {
	return m.recorder
}

// At mocks base method.
func (m *MockStartPart) At() time.Time {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "At")
	ret0, _ := ret[0].(time.Time)
	return ret0
}

// At indicates an expected call of At.
func (mr *MockStartPartMockRecorder) At() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "At", reflect.TypeOf((*MockStartPart)(nil).At))
}
