// Code generated by MockGen. DO NOT EDIT.
// Source: trontria.com/agentgo/models (interfaces: EndPart)
//
// Generated by this command:
//
//	mockgen -destination=../mocks/mock_end_part.go -package=mocks trontria.com/agentgo/models EndPart
//

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
	models "trontria.com/agentgo/models"
)

// MockEndPart is a mock of EndPart interface.
type MockEndPart struct {
	ctrl     *gomock.Controller
	recorder *MockEndPartMockRecorder
	isgomock struct{}
}

// MockEndPartMockRecorder is the mock recorder for MockEndPart.
type MockEndPartMockRecorder struct {
	mock *MockEndPart
}

// NewMockEndPart creates a new mock instance.
func NewMockEndPart(ctrl *gomock.Controller) *MockEndPart {
	mock := &MockEndPart{ctrl: ctrl}
	mock.recorder = &MockEndPartMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockEndPart) EXPECT() *MockEndPartMockRecorder {
	return m.recorder
}

// GetFinishReason mocks base method.
func (m *MockEndPart) GetFinishReason() models.FinishReason {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetFinishReason")
	ret0, _ := ret[0].(models.FinishReason)
	return ret0
}

// GetFinishReason indicates an expected call of GetFinishReason.
func (mr *MockEndPartMockRecorder) GetFinishReason() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetFinishReason", reflect.TypeOf((*MockEndPart)(nil).GetFinishReason))
}

// GetUsage mocks base method.
func (m *MockEndPart) GetUsage() models.LanguageModelUsage {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUsage")
	ret0, _ := ret[0].(models.LanguageModelUsage)
	return ret0
}

// GetUsage indicates an expected call of GetUsage.
func (mr *MockEndPartMockRecorder) GetUsage() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUsage", reflect.TypeOf((*MockEndPart)(nil).GetUsage))
}
