// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/nquangtrung/agentgo/providers/gemini (interfaces: geminiChatService)
//
// Generated by this command:
//
//	mockgen -destination=./mocks/mock_gemini_chat_service.go -package=mocks github.com/nquangtrung/agentgo/providers/gemini geminiChatService
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	openai "github.com/openai/openai-go/v3"
	option "github.com/openai/openai-go/v3/option"
	ssestream "github.com/openai/openai-go/v3/packages/ssestream"
	gomock "go.uber.org/mock/gomock"
)

// MockgeminiChatService is a mock of geminiChatService interface.
type MockgeminiChatService struct {
	ctrl     *gomock.Controller
	recorder *MockgeminiChatServiceMockRecorder
	isgomock struct{}
}

// MockgeminiChatServiceMockRecorder is the mock recorder for MockgeminiChatService.
type MockgeminiChatServiceMockRecorder struct {
	mock *MockgeminiChatService
}

// NewMockgeminiChatService creates a new mock instance.
func NewMockgeminiChatService(ctrl *gomock.Controller) *MockgeminiChatService {
	mock := &MockgeminiChatService{ctrl: ctrl}
	mock.recorder = &MockgeminiChatServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockgeminiChatService) EXPECT() *MockgeminiChatServiceMockRecorder {
	return m.recorder
}

// New mocks base method.
func (m *MockgeminiChatService) New(ctx context.Context, body openai.ChatCompletionNewParams, opts ...option.RequestOption) (*openai.ChatCompletion, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, body}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "New", varargs...)
	ret0, _ := ret[0].(*openai.ChatCompletion)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// New indicates an expected call of New.
func (mr *MockgeminiChatServiceMockRecorder) New(ctx, body any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, body}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "New", reflect.TypeOf((*MockgeminiChatService)(nil).New), varargs...)
}

// NewStreaming mocks base method.
func (m *MockgeminiChatService) NewStreaming(ctx context.Context, body openai.ChatCompletionNewParams, opts ...option.RequestOption) *ssestream.Stream[openai.ChatCompletionChunk] {
	m.ctrl.T.Helper()
	varargs := []any{ctx, body}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "NewStreaming", varargs...)
	ret0, _ := ret[0].(*ssestream.Stream[openai.ChatCompletionChunk])
	return ret0
}

// NewStreaming indicates an expected call of NewStreaming.
func (mr *MockgeminiChatServiceMockRecorder) NewStreaming(ctx, body any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, body}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "NewStreaming", reflect.TypeOf((*MockgeminiChatService)(nil).NewStreaming), varargs...)
}
