// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/nquangtrung/agentgo/providers/deepseek (interfaces: deepSeekResponsesService)
//
// Generated by this command:
//
//	mockgen -destination=./mocks/mock_deepseek_responses_service.go -package=mocks github.com/nquangtrung/agentgo/providers/deepseek deepSeekResponsesService
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	option "github.com/openai/openai-go/v3/option"
	ssestream "github.com/openai/openai-go/v3/packages/ssestream"
	responses "github.com/openai/openai-go/v3/responses"
	gomock "go.uber.org/mock/gomock"
)

// MockdeepSeekResponsesService is a mock of deepSeekResponsesService interface.
type MockdeepSeekResponsesService struct {
	ctrl     *gomock.Controller
	recorder *MockdeepSeekResponsesServiceMockRecorder
	isgomock struct{}
}

// MockdeepSeekResponsesServiceMockRecorder is the mock recorder for MockdeepSeekResponsesService.
type MockdeepSeekResponsesServiceMockRecorder struct {
	mock *MockdeepSeekResponsesService
}

// NewMockdeepSeekResponsesService creates a new mock instance.
func NewMockdeepSeekResponsesService(ctrl *gomock.Controller) *MockdeepSeekResponsesService {
	mock := &MockdeepSeekResponsesService{ctrl: ctrl}
	mock.recorder = &MockdeepSeekResponsesServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockdeepSeekResponsesService) EXPECT() *MockdeepSeekResponsesServiceMockRecorder {
	return m.recorder
}

// New mocks base method.
func (m *MockdeepSeekResponsesService) New(ctx context.Context, body responses.ResponseNewParams, opts ...option.RequestOption) (*responses.Response, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, body}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "New", varargs...)
	ret0, _ := ret[0].(*responses.Response)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// New indicates an expected call of New.
func (mr *MockdeepSeekResponsesServiceMockRecorder) New(ctx, body any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, body}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "New", reflect.TypeOf((*MockdeepSeekResponsesService)(nil).New), varargs...)
}

// NewStreaming mocks base method.
func (m *MockdeepSeekResponsesService) NewStreaming(ctx context.Context, body responses.ResponseNewParams, opts ...option.RequestOption) *ssestream.Stream[responses.ResponseStreamEventUnion] {
	m.ctrl.T.Helper()
	varargs := []any{ctx, body}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "NewStreaming", varargs...)
	ret0, _ := ret[0].(*ssestream.Stream[responses.ResponseStreamEventUnion])
	return ret0
}

// NewStreaming indicates an expected call of NewStreaming.
func (mr *MockdeepSeekResponsesServiceMockRecorder) NewStreaming(ctx, body any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, body}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "NewStreaming", reflect.TypeOf((*MockdeepSeekResponsesService)(nil).NewStreaming), varargs...)
}
